version: "3.8"

services:
  server:
    image: mehakpreet23/5-april-admin-server:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  client:
    image: mehakpreet23/5-april-admin-client:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
