version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
    # Uncomment if you need to set specific environment variables for the server

  client:
    build: ./ff/my-project # Ensure this points to the correct frontend directory
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./ff/my-project:/app
    # Uncomment if you need to set specific environment variables for the client
