
version: "3.8"

services:
  server:
    image: mehakpreet23/5-april-admin-server:latest  # Use the image from Docker Hub
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    # volumes:  # You can remove the volumes unless you want to mount a local directory for development
      # - ./server:/app

  client:
    image: mehakpreet23/5-april-admin-client:latest  # Use the image from Docker Hub
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # volumes:  # You can remove the volumes unless you want to mount a local directory for development
      # - ./ff/my-project:/ap
