version: '3'
services:
  client:
    image: admin-client-local:latest
    build:
      context: ./ff/my-project
    ports:
      - "3000:3000"

  server:
    image: admin-server-local:latest
    build:
      context: ./server
    ports:
      - "5000:5000"
